#!/usr/bin/env python
# encoding: utf-8
import sys
sys.path.append('waf_tools')
import builder

def build(bld):
  tst = bld.new_task_gen('cxx', 'program')
  tst.install_path = 0
  tst.env = bld.env_of_name('sdl').copy()
  tst.target = 'split_test'
  tst.find_sources_in_dirs('.')
  tst.includes = ' .'
  tst.uselib_local = 'bwt_default'
  tst.uselib = 'HOST'

