#!/usr/bin/python

host_libs = ''
if bld.env.variant().startswith('nds'):
    host_libs = 'NDS'
else:
    host_libs = 'GL SDL'

bld.add_subdirs('common/snd')
bld.add_subdirs('common/img')

bld.program('ChaosDS', 'arm9/source',
        uselib=host_libs,
        uselib_local='ndspp pal snd')
