#!/usr/bin/env python
# encoding: utf-8

import TaskGen

def build(bld):
  import os
  from builder import generate_banner

  bld.add_subdirs('common/img')
  bld.add_subdirs('common/snd')

  APPNAME = 'ChaosDS'
  arm9obj = bld.new_task_gen('cxx', 'staticlib')
  arm9obj.install_path = 0
  arm9obj.includes = 'arm9/source'
  arm9obj.export_incdirs = arm9obj.includes
  arm9obj.find_sources_in_dirs('arm9/source', ['main.cpp'])
  arm9obj.uselib_local = 'ndspp pal sounds '
  arm9obj.target = APPNAME
  arm9obj.uselib = 'HOST'

  if bld.env['WITH_SDL']:
    sdl = arm9obj.clone('sdl')


  arm7obj = bld.new_task_gen('cxx', 'program')
  arm7obj.install_path = 0
  arm7obj.includes = 'arm7/source'
  arm7obj.find_sources_in_dirs(arm7obj.includes)
  arm7obj.uselib = 'ARM7'
  arm7obj.uselib_local = 'ndspp-arm7'
  arm7elfname = APPNAME+'-arm7.elf'
  arm7obj.target = arm7elfname

  arm9p = bld.new_task_gen('cxx', 'program')
  arm9p.install_path = 0
  arm9p.source = 'arm9/source/main.cpp'
  arm9p.uselib_local = APPNAME+' ndspp'
  arm9p.uselib = 'HOST'
  arm9elfname = APPNAME+'-arm9.elf'
  arm9p.target = arm9elfname

  if bld.env['WITH_SDL']:
    sdlp = arm9p.clone('sdl')
    sdlp.target = APPNAME

  # generate nds
  TaskGen.task_gen(source=arm7elfname, install_path=0)
  TaskGen.task_gen(source=arm9elfname, install_path=0)
  nds = bld.new_task_gen('ndstool')
  nds.source = (arm7elfname.replace('.elf', '.arm'),
                arm9elfname.replace('.elf', '.arm'))
  nds.banner = generate_banner(APPNAME)
  nds.icon = 'common/data/icon_palette.bmp'
  nds.target = APPNAME+'.nds'
