#!/usr/bin/env python
# encoding: utf-8

def build(bld):
  import Params, os
  from builder import check_target, generate_banner

  bld.add_subdirs('common/img')
  bld.add_subdirs('common/snd')

  APPNAME = 'ChaosDS'
  arm9obj = bld.create_obj('cpp', 'staticlib')
  arm9obj.inst_var = 0
  arm9obj.includes = 'arm9/source'
  arm9obj.export_incdirs = arm9obj.includes
  arm9obj.find_sources_in_dirs('arm9/source', ['main.cpp'])
  arm9obj.uselib_local = 'ndspp pal sounds '
  arm9obj.target = APPNAME

  if bld.env()['WITH_SDL']:
    sdl = arm9obj.clone('sdl')
    sdl.uselib = 'HOST'

  arm9obj.uselib = 'ARM9'

  arm7obj = bld.create_obj('cpp', 'program')
  arm7obj.inst_var = 0
  arm7obj.includes = 'arm7/source'
  arm7obj.find_sources_in_dirs(arm7obj.includes)
  arm7obj.uselib = 'ARM7'
  arm7obj.uselib_local = 'ndspp-arm7'
  arm7obj.target = APPNAME+'-arm7'

  arm9p = bld.create_obj('cpp', 'program')
  arm9p.inst_var = 0
  arm9p.source = 'arm9/source/main.cpp'
  arm9p.uselib_local = APPNAME+' ndspp'
  arm9p.uselib = 'ARM9'
  arm9p.target = APPNAME+'-arm9'

  if bld.env()['WITH_SDL']:
    sdlp = arm9p.clone('sdl')
    sdlp.uselib = 'HOST'
    sdlp.target = APPNAME
    check_target(sdlp)

  # generate nds
  arm9bin = bld.create_obj('objcopy')
  arm9bin.inst_var = 0
  arm9bin.source = arm9p.target
  arm9bin.target = arm9p.target+'.bin'

  arm7bin = arm9bin.clone('default')
  arm7bin.inst_var = 0
  arm7bin.source = arm7obj.target
  arm7bin.target = arm7obj.target+'.bin'

  nds = bld.create_obj('ndstool')
  nds.source = (arm7bin.target, arm9bin.target)
  nds.banner = generate_banner(APPNAME)
  nds.icon = 'common/data/icon_palette.bmp'
  nds.target = APPNAME+'.nds'
  check_target(nds)
