#!/usr/bin/env python
# encoding: utf-8
import os
import Constants

def build(bld):
  obj = bld.new_task_gen('cxx', 'staticlib')
  if bld.env['WITH_SDL']:
    obj.install_path = 0
    obj.env = bld.env_of_name('sdl').copy()
    obj.source = '''Main.cpp'''
    obj.target = '''cppunitmain'''

  # build subdirs
  here = obj.path.abspath()
  [bld.add_subdirs(d) for d in os.listdir(here)
      if os.path.exists(os.path.join(here,d,Constants.WSCRIPT_FILE))]

  taskgens = []
  sources = """
               common/fonts/vera.img
               common/fonts/vera.map
               common/fonts/vera.pal
            """
  arm9font = bld.new_task_gen('cxx', 'staticlib')
  arm9font.target = 'vera'
  arm9font.install_path = 0
  arm9font.export_incdirs = '.'
  arm9font.source = sources
  # need to do this, or the objects are not added!
  [arm9font.add_obj_file(s+'.o') for s in sources.split()]
  taskgens.append(arm9font)

  hdr = bld.new_task_gen('name2h')
  hdr.target = 'vera.h'
  hdr.source = sources
  taskgens.append(hdr)

  if bld.env['WITH_SDL']:
    for t in taskgens: t.clone('sdl')
