#!/usr/bin/env python
# encoding: utf-8

arm9obj = bld.new_task_gen('cxx', 'staticlib')
arm9obj.inst_var = 0
arm9obj.includes = ' include img'
arm9obj.find_sources_in_dirs('source img')
arm9obj.target = 'bwt'
arm9obj.uselib_local = 'ndspp'
arm9obj.export_incdirs = 'include'

if bld.env['WITH_SDL']:
  sdl = arm9obj.clone('sdl')

