#!/usr/bin/env python
# encoding: utf-8


def build(bld):

  obj = bld.new_task_gen('cxx', 'staticlib')
  obj.gritflags = '-pw 16 -gB 4 -m! -ftc -fh -q -pe2 -pT 1'
  obj.install_path = 0
  obj.export_incdirs = 'include'
  obj.includes = 'include source/common'
  obj.target = 'ndspp'

  if bld.env['WITH_SDL']:
    sdl = obj.clone('sdl')
    sdl.includes += ' source/pc'
    sdl.find_sources_in_dirs('source/pc source/common')

  obj.includes += ' source/arm9'
  obj.find_sources_in_dirs('source/arm9 source/common')
  obj.uselib = 'HOST'
