#!/usr/bin/env python
# encoding: utf-8

import TaskGen
import Options

def build(bld):
  import os
  from builder import generate_banner

  APPNAME = 'bunjalloo'
  os.unsetenv('NDS_DLDI')
  arm9obj = bld.new_task_gen('cxx', 'staticlib')
  arm9obj.install_path = 0
  arm9obj.includes = 'arm9'
  arm9obj.export_incdirs = arm9obj.includes
  arm9obj.find_sources_in_dirs('arm9', ['Main.cpp'])
  arm9obj.uselib_local = 'ndspp bwt'
  arm9obj.target = APPNAME

  if bld.env['WITH_SDL']:
    sdl = arm9obj.clone('sdl')
    sdl.uselib = 'HOST'
  arm9obj.uselib = 'ARM9'

  arm7obj = bld.new_task_gen('cxx', 'program')
  arm7obj.install_path = 0
  arm7obj.includes = 'arm7'
  arm7obj.find_sources_in_dirs(arm7obj.includes)
  arm7obj.uselib = 'ARM7'
  arm7obj.uselib_local = 'ndspp-arm7'
  arm7elfname = APPNAME+'-arm7.elf'
  arm7obj.target = arm7elfname

  arm9p = bld.new_task_gen('cxx', 'program')
  arm9p.install_path = 0
  arm9p.source = 'arm9/Main.cpp'
  arm9p.uselib_local = APPNAME+' ndspp bwt '
  arm9p.uselib = 'ARM9'
  arm9elfname = APPNAME+'-arm9.elf'
  arm9p.target = arm9elfname

  if bld.env['WITH_SDL']:
    sdlp = arm9p.clone('sdl')
    sdlp.uselib = 'HOST'
    sdlp.target = APPNAME

  # generate nds
  TaskGen.task_gen(source=arm7elfname, install_path=0)
  TaskGen.task_gen(source=arm9elfname, install_path=0)
  nds = bld.new_task_gen('ndstool')
  nds.source = (arm7elfname.replace('.elf', '.arm'),
                arm9elfname.replace('.elf', '.arm'))
  nds.banner = generate_banner(APPNAME)
  nds.icon = 'common/data/icon.bmp'
  nds.target = APPNAME+'.nds'

  if bld.env['DLDIFLAGS']:
    patched = bld.new_task_gen('dlditool')
    patched.source = nds.target
    patched.target = APPNAME+'-patched.nds'

  bld.add_subdirs('bwt tests')

  if Options.options.install_to:
    bld.env['BUNJALLOO_PREFIX'] = Options.options.install_to
    bld.install_files('BUNJALLOO_PREFIX', '', nds.target)
    [bld.install_files('BUNJALLOO_PREFIX', 'data/bunjalloo/%s'%d, 'data/bunjalloo/%s/*'%d) for d in ('config', 'docs', 'fonts')]

