#!/usr/bin/env python
# encoding: utf-8

import TaskGen
import Options

def build(bld):
  import os
  from builder import generate_banner

  APPNAME = 'bunjalloo'
  os.unsetenv('NDS_DLDI')
  arm9obj = bld.new_task_gen('cxx', 'staticlib')
  arm9obj.install_path = 0
  arm9obj.includes = 'arm9'
  arm9obj.export_incdirs = arm9obj.includes
  arm9obj.find_sources_in_dirs('arm9', ['Main.cpp'])
  arm9obj.uselib_local = 'ndspp bwt'
  arm9obj.target = APPNAME
  arm9obj.uselib = 'HOST'

  if bld.env['WITH_SDL']:
    sdl = arm9obj.clone('sdl')

  arm9p = bld.new_task_gen('cxx', 'program')
  arm9p.install_path = 0
  arm9p.source = 'arm9/Main.cpp'
  arm9p.uselib_local = APPNAME+' ndspp bwt '
  arm9p.uselib = 'HOST'
  arm9elfname = APPNAME+'-arm9.elf'
  arm9p.target = arm9elfname

  if bld.env['WITH_SDL']:
    sdlp = arm9p.clone('sdl')
    sdlp.target = APPNAME

  # generate nds
  TaskGen.task_gen(source=arm9elfname, install_path=0)
  nds = bld.new_task_gen('ndstool')
  nds.source = arm9elfname.replace('.elf', '.arm')
  nds.banner = generate_banner(APPNAME, 'Web Browser')
  nds.icon = 'common/data/icon.bmp'
  nds.target = APPNAME+'.nds'

  if bld.env['DLDIFLAGS']:
    patched = bld.new_task_gen('dlditool')
    patched.source = nds.target
    patched.target = APPNAME+'-patched.nds'

  bld.add_subdirs('bwt tests')

  if Options.commands['install']:
    bld.install_files('${PREFIX}', nds.target)
    [bld.install_files('${PREFIX}/data/bunjalloo/%s'%d, 'data/bunjalloo/%s/*'%d) for d in ('config', 'docs', 'fonts', 'cert')]

